version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Containerfile   
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434   
  
  ollama:
    build:
      context: .
      dockerfile: Ollama.Dockerfile       
    ports:
      - "11434:11434"                     
   
